id: I2E16B6C6
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:10:08.709483
last_modified: 2023-02-08 15:10:08.709651
source_metadata:
  title: Laṅkāvatārasūtra
  language: zh
bases:
  25D5:
    base_file: 25D5.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
